/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CglcSyKSTlP
 */


export default function Practicepage() {
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <h1
        className="mt-8 mb-8 text-3xl font-bold text-center text-gray-700 dark:text-white">Practice Questions</h1>
      <div className="w-full max-w-md p-4 space-y-4">
        <div
          className="flex flex-col p-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
          <h2 className="text-lg font-semibold text-gray-700 dark:text-white">Question 1</h2>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
            Which of the following is not a programming language?
          </p>
          <div className="mt-4 space-y-2">
            <input
              className="w-full px-3 py-2 text-sm text-gray-700 bg-green-200 rounded-md dark:bg-green-700 dark:text-gray-300"
              placeholder="Option 1 (Correct)"
              type="text" />
            <input
              className="w-full px-3 py-2 text-sm text-gray-700 bg-red-200 rounded-md dark:bg-red-700 dark:text-gray-300"
              placeholder="Option 2 (Incorrect)"
              type="text" />
            <input
              className="w-full px-3 py-2 text-sm text-gray-700 bg-gray-200 rounded-md dark:bg-gray-700 dark:text-gray-300"
              placeholder="Option 3"
              type="text" />
            <input
              className="w-full px-3 py-2 text-sm text-gray-700 bg-gray-200 rounded-md dark:bg-gray-700 dark:text-gray-300"
              placeholder="Option 4"
              type="text" />
          </div>
          <div className="flex justify-between mt-6 space-x-4">
            <button
              className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-500 focus:outline-none focus:bg-indigo-500">
              Submit Answer
            </button>
            <button
              className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-500 focus:outline-none focus:bg-blue-500">
              Next Question
            </button>
          </div>
        </div>
      </div>
    </div>)
  );
}
