/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/J6nloxr3ynN
 */
// import Link from "next/link"

export default function Quizpage() {
  return (
    (<div key="1" className="bg-[#D3D3D3]">
      <nav className="bg-blue-400 shadow dark:bg-gray-800">
        <div className="container px-6 py-4 mx-auto">
          <div className="md:flex md:items-center md:justify-between">
            <div className="flex items-center justify-between">
              <div
                className="text-3xl font-bold text-white lg:text-3xl hover:text-gray-700 dark:hover:text-gray-300">
                <h1>QUIZ</h1>
                
              </div>
            </div>
          </div>
        </div>
      </nav>
      <div className="flex justify-center p-6 space-x-4">
        <a
          className="px-2 py-1 text-blue-400 bg-white rounded hover:bg-blue-400 hover:text-white"
          href="#">
          1
        </a>
        <a
          className="px-2 py-1 text-blue-400 bg-white rounded hover:bg-blue-400 hover:text-white"
          href="#">
          2
        </a>
        <a
          className="px-2 py-1 text-blue-400 bg-white rounded hover:bg-blue-400 hover:text-white"
          href="#">
          3
        </a>
        <a
          className="px-2 py-1 text-blue-400 bg-white rounded hover:bg-blue-400 hover:text-white"
          href="#">
          4
        </a>
        <a
          className="px-2 py-1 text-blue-400 bg-white rounded hover:bg-blue-400 hover:text-white"
          href="#">
          5
        </a>
      </div>
      <div
        className="max-w-3xl p-6 mx-auto my-8 space-y-6 bg-white rounded-lg shadow-md">
        <div className="pb-6 border-b border-gray-200" id="question1">
          <h2 className="text-2xl font-bold">Question 1</h2>
          <p className="mt-2 text--600black">What is a data structure?</p>
          <div className="mt-4 space-y-2">
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              1. A programming language
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              2. A collection of algorithms
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              3. A way to store and organize data
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              4. A type of computer hardware
            </button>
          </div>
        </div>
        <div className="pb-8 border-b border-gray-200" id="question2">
          <h2 className="text-2xl font-bold">Question 2</h2>
          <p className="mt-2 text-gray-600">What are the disadvantages of arrays?</p>
          <div className="mt-4 space-y-2">
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              1. Index value of an array can be negative
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              2. Elements are sequentially accessed
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              3. Data structure like queue or stack cannot be implemented
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              4. There are chances of wastage of memory space if elements inserted in an array are lesser than the
              allocated size
            </button>
          </div>
        </div>
        <div className="pb-8 border-b border-gray-200" id="question3">
          <h2 className="text-2xl font-bold">Question 3</h2>
          <p className="mt-2 text-gray-600">Which data structure is used for implementing recursion?</p>
          <div className="mt-4 space-y-2">
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              1. Stack
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              2. Queue
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              3. List
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              4. Array
            </button>
          </div>
        </div>
        <div className="pb-8 border-b border-gray-200" id="question4">
          <h2 className="text-2xl font-bold">Question 4</h2>
          <p className="mt-2 text-gray-600">
            The data structure required to check whether an expression contains a balanced parenthesis is?
          </p>
          <div className="mt-4 space-y-2">
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              1. Queue
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              2. Stack
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              3. Tree
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              4. Array
            </button>
          </div>
        </div>
        <div className="pb-8 border-b border-gray-200" id="question5">
          <h2 className="text-2xl font-bold">Question 5</h2>
          <p className="mt-2 text-gray-600">Which of the following is not the application of stack?</p>
          <div className="mt-4 space-y-2">
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              1. Data Transfer between two asynchronous process
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              2. Compiler Syntax Analyzer
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              3. Tracking of local variables at run time
            </button>
            <button
              className="w-full px-4 py-2 text-black bg-blue-200 rounded hover:bg-blue-500 focus:bg-blue-500 focus:text-white">
              4. A parentheses balancing program
            </button>
          </div>
        </div>
        
        <button
          className="mt-4 px-4 py-2 bg-[#3399ff] text-white rounded hover:bg-blue-600 focus:bg-blue-600 focus:text-white">
          Submit
        </button>
      </div>
     
    </div>)
  );
}
